### ISSUE TITLE
When i use any function, I got an error

### ISSUE THREAD

**Issue by HexValid** [hamish2014/FreeCAD_drawing_dimensioning#110]
Hi,

I recorded an video for explains this issue.

https://webmshare.com/3XAnD

Log:

`
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/previewDimension.py", line 152, in hoverMoveEvent
    XML = '<svg width="%i" height="%i"> %s </svg>' % (preview.drawingVars.width, preview.drawingVars.height, self.dimensionSvgFun( x, y ))
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 60, in centerLine_preview
    return d.SVGFun( *selections_to_svg_fun_args(selections), viewScale = d.viewScale, **d.dimensionConstructorKWs )
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 44, in centerLinesSVG
    return _centerLinesSVG( center, topLeft, bottomRight, viewScale, centerLine_len_dot, centerLine_len_dash, centerLine_len_gap, centerLine_width, centerLine_color, True, True )
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 37, in _centerLinesSVG
    if bottomRight <> None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
Traceback (most recent call last):
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/previewDimension.py", line 152, in hoverMoveEvent
    XML = '<svg width="%i" height="%i"> %s </svg>' % (preview.drawingVars.width, preview.drawingVars.height, self.dimensionSvgFun( x, y ))
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 60, in centerLine_preview
    return d.SVGFun( *selections_to_svg_fun_args(selections), viewScale = d.viewScale, **d.dimensionConstructorKWs )
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 44, in centerLinesSVG
    return _centerLinesSVG( center, topLeft, bottomRight, viewScale, centerLine_len_dot, centerLine_len_dash, centerLine_len_gap, centerLine_width, centerLine_color, True, True )
  File "/home/os/.FreeCAD/Mod/FreeCAD_drawing_dimensioning/centerLines.py", line 37, in _centerLinesSVG
    if bottomRight <> None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
`

**Comment by quazgar** [comment]
Possibly a duplicate of #106?
